// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCraQ85gncKPlhrIT2VsIwtevUBbvYgKkQ',
    appId: '1:47071374179:web:dfddd269e558c85f2d8156',
    messagingSenderId: '47071374179',
    projectId: 'luggo-485aa',
    authDomain: 'luggo-485aa.firebaseapp.com',
    storageBucket: 'luggo-485aa.firebasestorage.app',
    measurementId: 'G-CKM8MW6B0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFpOnBkroFJ0Y_D41wQ-d9EK3hUzBEOdc',
    appId: '1:47071374179:android:64107a5d0704457d2d8156',
    messagingSenderId: '47071374179',
    projectId: 'luggo-485aa',
    storageBucket: 'luggo-485aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuG6Mgx3foEAua5DlBkf98kUrcqM7pdkE',
    appId: '1:47071374179:ios:c0b99a7d4951242e2d8156',
    messagingSenderId: '47071374179',
    projectId: 'luggo-485aa',
    storageBucket: 'luggo-485aa.firebasestorage.app',
    iosBundleId: 'com.example.luggo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuG6Mgx3foEAua5DlBkf98kUrcqM7pdkE',
    appId: '1:47071374179:ios:c0b99a7d4951242e2d8156',
    messagingSenderId: '47071374179',
    projectId: 'luggo-485aa',
    storageBucket: 'luggo-485aa.firebasestorage.app',
    iosBundleId: 'com.example.luggo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCraQ85gncKPlhrIT2VsIwtevUBbvYgKkQ',
    appId: '1:47071374179:web:444f0dd94e4e32b62d8156',
    messagingSenderId: '47071374179',
    projectId: 'luggo-485aa',
    authDomain: 'luggo-485aa.firebaseapp.com',
    storageBucket: 'luggo-485aa.firebasestorage.app',
    measurementId: 'G-MZT3VWBNDS',
  );
}
